### ISSUE TITLE
Send agenda prior to meeting

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#15]
#### As a moderator I want to be able to send an agenda after preparation before the actual meeting to all invited users

- [x] Button "Send Agenda" on meeting area next to "Finalize".
- [x] The "Send Agenda" button is invisible for non-moderators
- [x] The "Send Agenda" button is invisible after finalization
- [x] Click on button will send all topic titles, but not the child items to all moderators, invited and "additional participants" per email
- [x] Order of topics in email is current WYSIWYG order in the minute
- [x] If the agenda was already sent a confirmation dialog should be confirmed before sending it again
