### ISSUE TITLE
Make participants checklist 2 column

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#209]
As a user I dont want 4Minitz to waste my precious screen realestate so that I can see more valuable info at once.

- [x] If screen is "desktop" width and we have >7 participants make participants list 2 column
- [x] On smartphones stick with one column!
- [x] Check manually on major browsers and different windows witdth: IE11, Edge, current FF, current Safari, current Chrome

No E2E needed!

Hint:
https://css-tricks.com/guide-responsive-friendly-css-columns/
http://stackoverflow.com/questions/36747969/why-does-column-count-break-bootstrap

**Comment by derwok** [comment]
![grafik](https://cloud.githubusercontent.com/assets/4393698/24757071/61156434-1ade-11e7-912c-0b2e2450bd2c.png)

**Comment by derwok** [comment]
Timeboxed: 1d
