### ISSUE TITLE
UI in different languages

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#30]
- [ ] $ meteor add gadicohen:messageformat
- [ ] Bring all English Strings to MessageFormat
- [ ] Add "NLS Test" to Definition of Done for future stories
- [ ] Add a pseudo-translation script "zz"-locale, that converts all english strings for example "Abcdefghij" into a 40% longer string "Abcdefghij1234" with "#" at start and end: "#Abcdefghij1234#"
- [ ] Switch to locale "zz" and check if all predefined UI strings are now pseudo-translated
- [ ] Create Locale for DE
- [ ] If String is missing in a specific language, drop back to english text resource
- [ ] Default Locale resprects Browser Settings
- [ ] Locale of browser may be over-ruleable via InApp User settings
- [ ] UI Language is configurable via MeetingSeries as "fixed", "suggest", "user-setting" (e.g., If Meeting - - [ ] language is English the mmoderator may may fix the UI language to English)

**Comment by jseverinod** [comment]
I can help to translate locale file on spanish

**Comment by MenDevNL** [comment]
I am willing to translate in Dutch.

Kind regard,

Menno Manheim

**Comment by itrich** [comment]
@jseverinod @MenDevNL Feel free to support the translation on https://crwd.in/4minitz

**Comment by itrich** [comment]
I'm not quite sure how to deal with strings containing HTML code. For instance, the string _"Licensed under the MIT-License"_ in the About dialog contains a href tag around the word MIT-License. We could now:

- Add the href around the whole string "Licensed under the MIT-License" and evade the use of `{{{ ... }}}`
- Split the string in two string "Licensed under the" and "MIT-License" and translating both separately. However, this is not possible for languages where the grammatical object ist not the last part of a sentence.
- Translate the string as "Licensed under the {$hrefOpen}MIT-License{$hrefClose}" and adding the href tag within the template. To do this, we need to disable purifying of strings and use triple mustache brackets, which may be misused by a translator to inject arbitrary code. 

Below is a screenshot of how the first solution would look like:
![newAbout](https://user-images.githubusercontent.com/29982899/67461585-f677e000-f63d-11e9-9536-5c7bbb434c56.png)

The same question applies to the QuickHelp sections. Should we seperate the HTML code from the translatable strings or do we include code within the translation making it more flexible?

What do you think and which solution would you prefer? Peering @derwok.

**Comment by derwok** [comment]
@derwok will take here...

## WIP for NLS / i18n
- [x] Make screenshots (English locale!) of ~~all~~ **most relevant** UI text elements (screens, dialogs, error flash messages), put them to a markdown file for manual testing. For each add a "how-to-get-there" information. 
- [x] Link screenshot collection to CrowdIn instructions for translators to check
- [x] HTML Files that need I18n of static strings
   - [x] confirmationDialogResetEdit.html
   - [x] connectioninfo.html
   - [x] legalNotice.html
   - [x] loginInfo.html
   - [x] login.html (only 'Coded with Love' footer)
   - [x] loginLdap.html (only 'Sign In' button)
- [x] Search for `ConfirmationDialogFactory.`to find & fix further static texts
- [x] JS Files that need I18n of static strings
   - [x] client/helpers/confirmationDialog.js
   - [x] client/helpers/confirmationDialogFactory.js
- [x] Search for `new FlashMessage` to find & fix further static texts
- [x] Remove tripple curlys from resource strings with variable injection to prevent malicious code to creep-in via user strings. Can we do this "test driven"? Insert a check into `tests/i18n/test_i18n_resources.js`. Maybe we can use markdown instead of triple curlys? See `client/templates/globals/confirmationDialog.html`already works like this!
- [x] Remove (C) `2015-2019` year numbers from resources
- [x] Plaintext only EMails (New user, New master version, Role change)
- [x] `imports/client/QualityTestRunner.js` returns checker results as static strings
- [x] Respect array of multiple prioritized accepted languages reported by browser. Map to first one we support
- [x] Remove unsupported custom message of `window.addEventListener('beforeunload')` code

## After merge to develop and translation of all new YAML strings to German
- [ ] Use `tests/i18n/manual/screenshots-en` screenshot collection and active German translation to find remaining static strings that need to be pulled to resource files

## Maybe "never" we will do:
- [ ] The DateTimePicker on `minutesedit.js` is configured static to English 'en' via moment.js. We need to configure moment.js with locales. e.g. `import momentde from 'moment/locale/de';` and then moment.locale() needs to use i18n.locale() instead of static 'en'
- [ ] Search for `new Meteor.Error` to find & fix further static texts. Attention: Most of them never shown to user - only logged to client/server console. But e.g.: `new Meteor.Error(403, 'User account is inactive!');`this one is shown in browser UI.
