### ISSUE TITLE
Binary Attachments

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#34]
## Backend
- [X] Research: File-Handling Packages (CollectionFS, Meteor-Files, roll-our-own, gridFS)
        => The winner is: https://github.com/VeliovGroup/Meteor-Files
- [X] Integrate Meteor-Files into project
- [X] Store uploads in subdirectories per meeting series (to avoid clutter & too many files in one dir)
- [X] Add minutesID & seriesID to meta-data of uloaded files
- [X] Filter collection publish on serverside by visible meeting series per user
- [x] settings.json with: on&off, storagePath, maxFilesize, allow/deny extension
- [X] Indroduce "Uploader" role to userroles
- [x] immediate return from upload/remove/download methods of user is not allowed to do so
- [X] Always(!) prohibit uploads of html / htm files. Regardless of settings.json config See XSS vulnerability VeliovGroup/Meteor-Files#289
- [x] server startup: check storagePath for write access. Log Error & switch-off Upload if no write access
- [x] Refactor Attachment.js facade
- [x] On delete of Minutes/Series => delete according attachments also

## Frontend
- [X] Display only attachments für current visible minutes
- [X] Show paperclip icon on minutes-date-list
- [X] Allow Upload/Remove of File. Show Yes/No-Msgbox before remove
- [X] Allow Cancel of upload & show Progressbar and remaining time during upload
- [x] Nice error popup if upload candidate is not allowed for some reasons.
- [x] Show/hide attachment buttons on: userrole, settings.json, isFinalized state
- [x] Show username behind every attachment file name
- [x] On attachment tooltip show: upload timestamp, filesize in bytes/MB
- [x] Expand/Collapse upload area
- [x] Server Stats show #attachment and total MBytes
- [x] Attachments to Meeting Minutes EMail

### Mixed
- [x] Put feature on "login screen info block"
- [x] Update AdminDoc on settings.json regarding attachments
- [ ] Update UserDoc on upload attachments feature

### E2E Tests
- [ ] Basic upload / download test
- [ ] Check role based visibility of buttons
- [ ] Check role based visibility of download URLs

### Future ideas
- [ ] Upload via dropzone
- [ ] Drop-Down-Menu with download/view/rename/delete
- [ ] Allow settings.json to switch to gridFS storage backend (without migration!)
- [ ] View images directly "in app"
- [ ] MeetingSeries details page shows list of all attachments in all meetings chronologically with upload-date & -user
- [ ] Offer possibility to send an attachement with the finalize mail. With (1) a checkbox at the attachment and (2) via question after click on finalize button.
