### ISSUE TITLE
User-Settings Dialog

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#35]
ACs
- [x] User Settings Accessible via current "User Logout" Menu
- [x] Pushdown logout menu one level (adapt E2E tests for logout() and isLoggedIn())
- [ ] Add "Settings" menu
- [x] Offer possibility to change password
- [ ] Offer possibility to add Company & Department
- [ ] Show Department (+Company) in UserEditor??
- [ ] Adapt LDAP import script to import to store company & department

## Future Ideas: 
- [ ] Offer possibility to select UI language
- [ ] Configure, if ActionItems are send to me as seperate Mails per AI or one big mail with all AIs (or even switch off AI Mails??!)

**Comment by derwok** [comment]
Will be realized by slightly smaller story #210
