### ISSUE TITLE
LDAP/AD Login-Support

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#41]
As an enterprise user I can login with my LDAP/AD password so that I do not have to remember indiviusl passwords for all my different web accounts
- [x] check out https://github.com/JackAdams/meteor-accounts-ldap
- [x] LDAP support can be switched on/off via settings.json 
- [x] enter example to settings_sample.json
- [x] User long name is drawn from LDAP
- [x] LDAP users are "copied" to meteor and enriched with 4minitz roles etc.
- [x] If user changes password on ladap she can login with the new password in 4minitz
- [x] It is possible to create non-ldap users with the normal "Register" functionality
- [x] Extend login UI in case ldap is activated (Tabs: LDAP, Standard)
- [x] Provide a script to sync ldap users with the meteor database
- [x] Prevent LDAP users from logging in via local accounts
- [x] Add a chapter to he adminguide describing how to configure LDAP
- [x] Test everything

**Comment by derwok** [comment]
Maybe also https://github.com/etyp/meteor-accounts-ldap should get a closer look. It's the winner for an "LDAP" search on FastoSpere http://fastosphere.meteorapp.com/typ%253Aaccounts-ldap?q=ldap

**Comment by migerh** [comment]
Todo:

- [ ] Extend login UI in case ldap is activated (Tabs: LDAP, Standard)
- [ ] Extend user search to LDAP database -OR- provide a script to copy all ldap users over to the meteor database
- [ ] Prevent LDAP users from logging in via local accounts

**Comment by migerh** [comment]
Todo:
- [ ] Test everything

**Comment by migerh** [comment]
If anyone wants to try, you can test it with this publically available ldap server:

    "ldap": {
        "enabled": true,
        "searchDn": "uid",
        "searchFilter": "(objectClass=inetOrgPerson)",
        "serverDn": "DC=example,DC=com",
        "serverUrl": "ldap://ldap.forumsys.com",
        "allowSelfSignedTLS": true,
        "whiteListedFields": [ "uid", "cn", "mail" ],
        "autopublishFields": [ "uid", "cn" ]
    }

Infos about this server: http://www.forumsys.com/en/tutorials/integration-how-to/ldap/online-ldap-test-server/

To import user database

- add above config to end2end settings file
- start meteor end2end server
- run the import script

    node ./private/ldap/importUsers.js -s settings-test-end2end.json -m mongodb://localhost:3101/meteor

- login with e.g. einstein/password
