### ISSUE TITLE
Start/Stop Time for Meetings / Topics

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#51]
As a moderator I want to plan and lead the meeting time-based to increase efficiency for all
A Meeting can have a start / stop time / duration
A progressbar shows the elapsed time + values for "passed time" & "remaining time" hh:mm
Optionally topics can get durations
App caluclates start/stop time of topics automatically
start/stop times of the minutes & all active topics are part of "Send Agenda" mail

**Comment by derwok** [comment]
@terryb8s brough this up again in #405.
I see the problem here that many moderators can live without this feature. So how do we prohibit that this clutters their UI? This is the main reason we postponed this issue a few times.

A more simple solution could be: 
a global **Countdown Timer** per Meeting Minutes.

- [ ] Timer can be changed only by moderators
- [ ] Timer can be setup at "top area" of meeting series.
- [ ] Timer can be initialized with hh:mm
- [ ] Timer has spin up/down buttons (+/- 5 min)
- [ ] Timer has Start/Stop/Pause buttons
- [ ] Timer is "sticky visible" regardless of scroll position
- [ ] Timer shows reactively the same time for all users on the same meeting
- [ ] Timer is killed on Minutes Finalize
- [ ] UI-candy: Timer shows shrinking progress bar

Benefits:
* More easy to implement
* Only small UI space required if not needed

Further ideas? Will this work?

**Comment by terryb8s** [comment]
In terms of UI clutter the easy solution in my mind would be to have this feature as optional and defined in the meeting series properties, that way users who don't want it wont enable it, this option should be set to disabled by default.

In my opinion a global timer would have very little purpose except for replacing my watch or phone, the reasoning behind my request is to keep people on topic and preventing other topics from being missed because of this.

Shrinking progress bar is a nice touch but I don't think this is required as you really just want to know how much time is left if you are looking at it.

Labels or a ranking could be used to define what fraction of time a topic should take? 

I like the rest of what you have described I think it would be really good.

Cheers
P.S. Crazy thought... Maybe the timer could be announced by a google assistant or something similar, rather than displayed on the UI or options for both?
